name: owl_clean
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  intl: ^0.20.2
  table_calendar: ^3.0.9
  video_player: ^2.8.2
  uuid: ^4.0.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/

# アプリアイコン設定（追加）
flutter_launcher_icons:
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true